#!/bin/bash

# Looks for changes between live dotfiles and the repository.
# Useful to keep these places separate for testing and staging
# before committing them to the repo and further upstream.

cd ~/.dotfiles/
for file in `find . -type f | grep -vE '(\.git|README|LICENSE|bootstrap\.sh)' | cut -c 2-`; do
	diff -qr .${file} ${HOME}${file} | awk '{print $2}';
done
