#!/bin/bash

# Set up new directory for CAP development in a container
# using VS Code Remote Development feature. This copies a
# devcontainer definition that is defined for this purpose.

SOURCE=$LP/devcontainer-cap-dev
TARGET=$1

# Abort if directory exists already
if [ -d ${TARGET} ]; then
	echo Aborting, target directory ${TARGET} already exists.
	exit 1
fi

cp -a ${SOURCE} ${TARGET}
$CODE ${TARGET}
